#pragma once

#include "CoreMinimal.h"

/** Named boat loft exports under Content/Data (Phase 3 generative builder). */
struct FBoatPreset
{
	FString Id;
	FString DisplayName;
	FString JsonRelativePath;
};

struct FBoatPresets
{
	static TArray<FBoatPreset> All()
	{
		// Generated by Scripts/export_boat3d_presets.py from sail-sim boat-spec catalog.
		return {
			{ TEXT("j105"), TEXT("J/105"), TEXT("Data/j105_boat3d.json") },
			{ TEXT("endeavour"), TEXT("Endeavour"), TEXT("Data/endeavour_boat3d.json") },
			{ TEXT("melges24"), TEXT("Melges 24"), TEXT("Data/melges24_boat3d.json") },
			{ TEXT("cruiser36"), TEXT("Cruiser 36"), TEXT("Data/cruiser36_boat3d.json") },
		};
	}

	static const FBoatPreset* Find(const FString& Id)
	{
		static TArray<FBoatPreset> Cache = All();
		for (const FBoatPreset& P : Cache)
		{
			if (P.Id.Equals(Id, ESearchCase::IgnoreCase))
			{
				return &P;
			}
		}
		return nullptr;
	}
};
